### ISSUE TITLE
Async

### ISSUE THREAD

**Issue by nharn85** [borisschapira/preloadr#3]
Async does not return the src. It's always undefined even in your example.html.

**Comment by borisschapira** [comment]
Oh! Thanks a lot for pointing that!

**Comment by diachedelic** [comment]
I think that fix breaks the API?  I need to call something like:

`preloadr([{ src: 'http://img' }])` 

rather than the documented 

`preloadr(['http://img'])`

**Comment by diachedelic** [comment]
Oh I see, the committed minified JS file behaves differently to the non-minified version!

**Comment by borisschapira** [comment]
@diachedelic thanks a lot for telling me!
